package com.cnpat.pdsc.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookDataRecord generated by hbm2java
 */
@Entity
@Table(name = "tbl_BookDataRecord", catalog = "PDSC_Management_DB")
public class BookDataRecord implements java.io.Serializable {

	private static final long serialVersionUID = -5174323993825961838L;
	
	private long bookRecordId;
	private Date createTime;

	public BookDataRecord() {
	}

	public BookDataRecord(long bookRecordId, Date createTime) {
		this.bookRecordId = bookRecordId;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "BookRecordID", unique = true, nullable = false)
	public long getBookRecordId() {
		return this.bookRecordId;
	}

	public void setBookRecordId(long bookRecordId) {
		this.bookRecordId = bookRecordId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
