package com.cnpat.pdsc.entity;

// Generated 2014-7-22 16:49:35 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookDataInfo generated by hbm2java
 */
@Entity
@Table(name = "BookDataInfo", catalog = "PDSC_Management_DB")
public class BookDataInfo implements java.io.Serializable {

	private static final long serialVersionUID = -8138325569112691658L;

	@Id
	@Column(name = "BookID", unique = true, nullable = false)
	private long bookId;

	@Column(name = "Url", nullable = false, length = 20)
	private String url;

	@Column(name = "Status", nullable = false)
	private int status;

	@Column(name = "ServiceType", nullable = false)
	private int serviceType;

	@Column(name = "Descript", length = 100)
	private String descript;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 19)
	private Date createTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", length = 19)
	private Date modifyTime;

	@OneToMany(cascade = { CascadeType.ALL })
	@JoinColumn(name = "Parent_ID", nullable = false)
	private Set<BookDataContent> contents;

	public long getBookId() {
		return this.bookId;
	}

	public void setBookId(long bookId) {
		this.bookId = bookId;
	}

	public final String getUrl() {
		return url;
	}

	public final void setUrl(String url) {
		this.url = url;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public int getServiceType() {
		return serviceType;
	}

	public void setServiceType(int serviceType) {
		this.serviceType = serviceType;
	}

	public final Set<BookDataContent> getContents() {
		return contents;
	}

	public final void setContents(Set<BookDataContent> contents) {
		this.contents = contents;
	}

}
