package com.cnpat.pdsc.entity;

// Generated 2014-7-22 16:49:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBookDataInfo generated by hbm2java
 */
@Entity
@Table(name = "tbl_BookDataInfo", catalog = "PDSC_Management_DB")
public class BookDataInfo implements java.io.Serializable {

	private static final long serialVersionUID = -8138325569112691658L;

	private long bookId;
	private String sourceIp;
	private int status;
	private String descript;
	private Date createTime;
	private Date modifyTime;

	public BookDataInfo() {
	}

	public BookDataInfo(long bookId, String sourceIp, int status,
			Date createTime, Date modifyTime) {
		this.bookId = bookId;
		this.sourceIp = sourceIp;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	public BookDataInfo(long bookId, String sourceIp, int status,
			String descript, Date createTime, Date modifyTime) {
		this.bookId = bookId;
		this.sourceIp = sourceIp;
		this.status = status;
		this.descript = descript;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@Column(name = "BookID", unique = true, nullable = false)
	public long getBookId() {
		return this.bookId;
	}

	public void setBookId(long bookId) {
		this.bookId = bookId;
	}

	@Column(name = "SourceIP", nullable = false, length = 20)
	public String getSourceIp() {
		return this.sourceIp;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "Descript", length = 100)
	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyTime", nullable = false, length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
