package com.cnpat.pdsc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblBookDataRecordDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_BookDataRecordDetail", catalog = "PDSC_Management_DB")
public class BookDataRecordDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6272580675775688199L;

	@Id
	private int opType;
	private long bookRecordId;
	private int dataType;

	public BookDataRecordDetail() {
	}

	public BookDataRecordDetail(int opType, long bookRecordId, int dataType) {
		this.opType = opType;
		this.bookRecordId = bookRecordId;
		this.dataType = dataType;
	}

	public long getBookRecordId() {
		return bookRecordId;
	}

	public void setBookRecordId(long bookRecordId) {
		this.bookRecordId = bookRecordId;
	}

	public int getDataType() {
		return dataType;
	}

	public void setDataType(int dataType) {
		this.dataType = dataType;
	}

	@Column(name = "OpType", nullable = false)
	public int getOpType() {
		return this.opType;
	}

	public void setOpType(int opType) {
		this.opType = opType;
	}

}
