package com.cnpat.pdsc.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblCoreDataBatchInfo generated by hbm2java
 */
@Entity
@Table(name = "CoreDataBatchInfo", catalog = "PDSC_Management_DB")
public class CoreDataBatchInfo implements java.io.Serializable {

	private static final long serialVersionUID = -303579121657850697L;
	
	private int dataType;
	private String batchNo;

	public CoreDataBatchInfo() {
	}

	public CoreDataBatchInfo(int dataType, String batchNo) {
		this.dataType = dataType;
		this.batchNo = batchNo;
	}

	@Id
	@Column(name = "DataType", unique = true, nullable = false)
	public int getDataType() {
		return this.dataType;
	}

	public void setDataType(int dataType) {
		this.dataType = dataType;
	}

	@Column(name = "BatchNo", nullable = false, length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

}
