package com.cnpat.pdsc.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCoreDataInfo generated by hbm2java
 */
@Entity
@Table(name = "CoreDataInfo", catalog = "PDSC_Management_DB")
public class CoreDataInfo implements java.io.Serializable {

	private static final long serialVersionUID = -9176612877121680046L;

	@Id
	@Column(name = "DataType", unique = true, nullable = false)
	private int dataType;

	@Column(name = "Name", nullable = false, length = 20)
	private String name;

	@Column(name = "DetailTblName", nullable = false, length = 50)
	private String detailTblName;

	@Column(name = "DetailEntityName", nullable = false, length = 50)
	private String detailEntityName;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 19)
	private Date createTime;

	@Column(name = "CurrentSeq", nullable = false)
	private int currentSeq;

	@Column(name = "TotalNum", nullable = false)
	private int totalNum;

	@Column(name = "TotalBatch", nullable = false)
	private int totalBatch;

	public CoreDataInfo() {
	}

	public CoreDataInfo(int dataType, String name, String detailTblName,
			Date createTime, int currentSeq, int totalNum, int totalBatch) {
		this.dataType = dataType;
		this.name = name;
		this.detailTblName = detailTblName;
		this.createTime = createTime;
		this.currentSeq = currentSeq;
		this.totalNum = totalNum;
		this.totalBatch = totalBatch;
	}

	public int getDataType() {
		return this.dataType;
	}

	public void setDataType(int dataType) {
		this.dataType = dataType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDetailTblName() {
		return this.detailTblName;
	}

	public void setDetailTblName(String detailTblName) {
		this.detailTblName = detailTblName;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public int getCurrentSeq() {
		return this.currentSeq;
	}

	public void setCurrentSeq(int currentSeq) {
		this.currentSeq = currentSeq;
	}

	public int getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(int totalNum) {
		this.totalNum = totalNum;
	}

	public int getTotalBatch() {
		return this.totalBatch;
	}

	public void setTotalBatch(int totalBatch) {
		this.totalBatch = totalBatch;
	}

	public String getDetailEntityName() {
		return detailEntityName;
	}

	public void setDetailEntityName(String detailEntityName) {
		this.detailEntityName = detailEntityName;
	}

}
