package com.cnpat.pdsc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblUpdateBibNow generated by hbm2java
 */
@Entity
@Table(name = "tbl_UpdateBibNow", catalog = "PDSC_Management_DB")
public class TblUpdateBibNow implements java.io.Serializable {

	private static final long serialVersionUID = -629354807937586482L;

	private long bibNowSeq;
	private long globalSeq;
	private String updateId;

	public TblUpdateBibNow() {
	}

	public TblUpdateBibNow(long bibNowSeq, long globalSeq, String updateId) {
		this.bibNowSeq = bibNowSeq;
		this.globalSeq = globalSeq;
		this.updateId = updateId;
	}

	@Id
	@Column(name = "BibNowSeq", unique = true, nullable = false)
	public long getBibNowSeq() {
		return this.bibNowSeq;
	}

	public void setBibNowSeq(long bibNowSeq) {
		this.bibNowSeq = bibNowSeq;
	}

	@Column(name = "GlobalSeq", nullable = false)
	public long getGlobalSeq() {
		return this.globalSeq;
	}

	public void setGlobalSeq(long globalSeq) {
		this.globalSeq = globalSeq;
	}

	@Column(name = "UpdateID", nullable = false, length = 20)
	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

}
