package com.cnpat.pdsc.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUpdateMain generated by hbm2java
 */
@Entity
@Table(name = "tbl_UpdateMain", catalog = "PDSC_Management_DB")
public class TblUpdateMain implements java.io.Serializable {

	private static final long serialVersionUID = -4973990127727936484L;

	private long globalSeq;
	private long localSeq;
	private int dataType;
	private int opType;
	private String batchNo;
	private Date createTime;
	private boolean rollbackFlag;
	private Long rollbackSeq;
	private int recordNum;

	public TblUpdateMain() {
	}

	public TblUpdateMain(long globalSeq, long localSeq, int dataType,
			int opType, String batchNo, Date createTime, boolean rollbackFlag,
			int recordNum) {
		this.globalSeq = globalSeq;
		this.localSeq = localSeq;
		this.dataType = dataType;
		this.opType = opType;
		this.batchNo = batchNo;
		this.createTime = createTime;
		this.rollbackFlag = rollbackFlag;
		this.recordNum = recordNum;
	}

	public TblUpdateMain(long globalSeq, long localSeq, int dataType,
			int opType, String batchNo, Date createTime, boolean rollbackFlag,
			Long rollbackSeq, int recordNum) {
		this.globalSeq = globalSeq;
		this.localSeq = localSeq;
		this.dataType = dataType;
		this.opType = opType;
		this.batchNo = batchNo;
		this.createTime = createTime;
		this.rollbackFlag = rollbackFlag;
		this.rollbackSeq = rollbackSeq;
		this.recordNum = recordNum;
	}

	@Id
	@Column(name = "GlobalSeq", unique = true, nullable = false)
	public long getGlobalSeq() {
		return this.globalSeq;
	}

	public void setGlobalSeq(long globalSeq) {
		this.globalSeq = globalSeq;
	}

	@Column(name = "LocalSeq", nullable = false)
	public long getLocalSeq() {
		return this.localSeq;
	}

	public void setLocalSeq(long localSeq) {
		this.localSeq = localSeq;
	}

	@Column(name = "DataType", nullable = false)
	public int getDataType() {
		return this.dataType;
	}

	public void setDataType(int dataType) {
		this.dataType = dataType;
	}

	@Column(name = "OpType", nullable = false)
	public int getOpType() {
		return this.opType;
	}

	public void setOpType(int opType) {
		this.opType = opType;
	}

	@Column(name = "BatchNo", nullable = false, length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "RollbackFlag", nullable = false)
	public boolean isRollbackFlag() {
		return this.rollbackFlag;
	}

	public void setRollbackFlag(boolean rollbackFlag) {
		this.rollbackFlag = rollbackFlag;
	}

	@Column(name = "RollbackSeq")
	public Long getRollbackSeq() {
		return this.rollbackSeq;
	}

	public void setRollbackSeq(Long rollbackSeq) {
		this.rollbackSeq = rollbackSeq;
	}

	@Column(name = "RecordNum", nullable = false)
	public int getRecordNum() {
		return this.recordNum;
	}

	public void setRecordNum(int recordNum) {
		this.recordNum = recordNum;
	}

}
