package com.cnpat.pdsc.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUpdatePatentPic generated by hbm2java
 */
@Entity(name = "UpdatePatentPic")
@Table(name = "tbl_UpdatePatentPic", catalog = "PDSC_Management_DB")
public class UpdatePatentPic implements java.io.Serializable, UpdateEntity {

	private static final long serialVersionUID = -3978686266417234381L;

	@Id
	@GeneratedValue
	@Column(name = "ID")
	private long id;

	@Column(name = "Seq", unique = true, nullable = false)
	private int seq;

	@ManyToOne
	@JoinColumn(name = "GlobalSeq")
	private UpdateMain updateMain;

	@Column(name = "UpdateID", nullable = false, length = 20)
	private String updateId;

	public UpdatePatentPic() {
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	public UpdateMain getUpdateMain() {
		return updateMain;
	}

	public void setUpdateMain(UpdateMain updateMain) {
		this.updateMain = updateMain;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
}
